### ISSUE TITLE
TestContinuousAgg2StepAgg requires Toolkit

### ISSUE THREAD

**Issue by jgpruitt** [timescale/promscale_extension#100]
The `TestContinuousAgg2StepAgg` test is failing in dev because the docker image we are testing with does not contain the timescaledb toolkit extension

**Comment by cevian** [comment]
Blocked on https://github.com/timescale/o11y-team-data-platform/issues/17

**Comment by JamesGuthrie** [comment]
This has been fixed (at least in CI).
