### ISSUE TITLE
Old non-versioned promscale.so file needs to be in new promscale_extension image as well. 

### ISSUE THREAD

**Issue by cevian** [timescale/promscale_extension#113]
The old non-versioned promscale.so file needs to exist in the new promscale_extension image (maybe). This is to enable transitions from the old to the new version to run smoothly. Without this, the docker image will be unusable until an `alter extension promscale upgrade` occurs. 

This is also gonna be required for older promscale versions once promscale versioned .so are a thing. We'll need to keep X previous versioned .so files in the docker image. Toolkit needs [to do the same ](https://github.com/timescale/timescaledb-docker-ha/blob/master/build_scripts/install_timescaledb-toolkit.sh).

We can probably build upon previous docker images in the short term.

**Comment by cevian** [comment]
@JamesGuthrie the issue is for non-docker images where you'll only have .so for versions that have been previously installed so if you are going from 0.12.0 to 0.14.0 and have never installed 0.13.0 you'll be missing that .so

**Comment by cevian** [comment]
I think this issue is conflating 2 things.

**Comment by cevian** [comment]
@sumerman can this be closed?

**Comment by sumerman** [comment]
yeah.
