### ISSUE TITLE
Have a plan for updating functions associated with idempotent types

### ISSUE THREAD

**Issue by JamesGuthrie** [timescale/promscale_extension#124]
This snippet (from here https://github.com/timescale/promscale_extension/pull/108/files#diff-b416afdda09bb869ae1b2ce78a3388f5386eb1c5135ff1bccaa24c3029591325R15) will break on extension upgrade unless the in/out functions are redefined in the extension idempotent part. We don't have a mechanism to ensure that this happens (yet).

```SQL
CREATE TYPE _prom_ext.GapfillDeltaTransition;

CREATE OR REPLACE FUNCTION _prom_ext."gapfilldeltatransition_in"(
	"input" cstring /* &cstr_core::CStr */
) RETURNS _prom_ext.GapfillDeltaTransition /* promscale::aggregates::gapfill_delta::GapfillDeltaTransition */
IMMUTABLE PARALLEL SAFE STRICT
LANGUAGE c /* Rust */
AS '$libdir/promscale-0.5.0', 'gapfilldeltatransition_in_wrapper';

CREATE OR REPLACE FUNCTION _prom_ext."gapfilldeltatransition_out"(
	"input" _prom_ext.GapfillDeltaTransition /* promscale::aggregates::gapfill_delta::GapfillDeltaTransition */
) RETURNS cstring /* &cstr_core::CStr */
IMMUTABLE PARALLEL SAFE STRICT
LANGUAGE c /* Rust */
AS '$libdir/promscale-0.5.0', 'gapfilldeltatransition_out_wrapper';

CREATE TYPE _prom_ext.GapfillDeltaTransition (
	INTERNALLENGTH = variable,
	INPUT = _prom_ext.gapfilldeltatransition_in, /* promscale::aggregates::gapfill_delta::gapfilldeltatransition_in */
	OUTPUT = _prom_ext.gapfilldeltatransition_out, /* promscale::aggregates::gapfill_delta::gapfilldeltatransition_out */
	STORAGE = extended
); 
```

**Comment by JamesGuthrie** [comment]
It is possible to configure a custom sql-generating function which only spits out the function definition for such types. This SQL could be used in an "idempotent" fashion. What is still not quite clear to me is how to handle this in the general case.

Ideally we'd have something like this:

- C-related migration
- C-related idempotent
- hand-written migration
- hand-written idempotent

Then we could split a definition as above into two components, a generic, C-independent type and function declaration:

```SQL
-- 001-gapfill-delta-type.sql
CREATE TYPE _prom_ext.GapfillDeltaTransition;

CREATE OR REPLACE FUNCTION _prom_ext."gapfilldeltatransition_in"("input" cstring) RETURNS _prom_ext.GapfillDeltaTransition
IMMUTABLE PARALLEL SAFE STRICT
LANGUAGE SQL AS $$
-- TODO STUB
$$;

CREATE OR REPLACE FUNCTION _prom_ext."gapfilldeltatransition_out"("input" _prom_ext.GapfillDeltaTransition) RETURNS cstring
IMMUTABLE PARALLEL SAFE STRICT
LANGUAGE SQL AS $$
-- TODO STUB
$$;

CREATE TYPE _prom_ext.GapfillDeltaTransition (
	INTERNALLENGTH = variable,
	INPUT = _prom_ext.gapfilldeltatransition_in
	OUTPUT = _prom_ext.gapfilldeltatransition_out
	STORAGE = extended
); 
```

And an idempotent C-dependent function re-declaration:
```SQL
-- idempotent SQL-C
CREATE OR REPLACE FUNCTION _prom_ext."gapfilldeltatransition_in"(
	"input" cstring /* &cstr_core::CStr */
) RETURNS _prom_ext.GapfillDeltaTransition /* promscale::aggregates::gapfill_delta::GapfillDeltaTransition */
IMMUTABLE PARALLEL SAFE STRICT
LANGUAGE c /* Rust */
AS '$libdir/promscale-0.5.0', 'gapfilldeltatransition_in_wrapper';

CREATE OR REPLACE FUNCTION _prom_ext."gapfilldeltatransition_out"(
	"input" _prom_ext.GapfillDeltaTransition /* promscale::aggregates::gapfill_delta::GapfillDeltaTransition */
) RETURNS cstring /* &cstr_core::CStr */
IMMUTABLE PARALLEL SAFE STRICT
LANGUAGE c /* Rust */
AS '$libdir/promscale-0.5.0', 'gapfilldeltatransition_out_wrapper';
```

**Comment by JamesGuthrie** [comment]
On templating of the SO path: We might be able to use PGX's `@MODULE_PATHNAME@` templating, which was added in PGX 0.4.4.

**Comment by sumerman** [comment]
What's the plan for `AS '$libdir/promscale-0.5.0', 'gapfilldeltatransition_in_wrapper';` that is already a part of incremental? AFAIK it'll break for anyone who doesn't have `promscale-0.5.0.so` present on their system.

**Comment by JamesGuthrie** [comment]
It is part of the incremental, and we will have to change it retroactively.

**Comment by JamesGuthrie** [comment]
I experimented with "stubbing" the functions, as suggested in a previous comment but it doesn't work.

The overall plan is going to be:

- add type and associated functions in incremental migration, with `.so` version templated (either with PGX `@MODULE_PATHNAME@` templating, or we use templating in our code)
- add same function in idempotent (`014-extension-type-functions.sql`), also with `.so` version templated.

**Comment by JamesGuthrie** [comment]
Closing as done. We have a plan, and have an issue for the implementation.
