### ISSUE TITLE
takeover scripts: correctly migrates extension as tested by upgrade tests

### ISSUE THREAD

**Issue by cevian** [timescale/promscale_extension#127]

**Comment by cevian** [comment]
will be fixed by https://github.com/timescale/promscale_extension/pull/152/files

**Comment by jgpruitt** [comment]
I believe so. The upgrade tests are passing, but they don't check absolutely everything. I want to use this issue to remind me to give it a relook

**Comment by cevian** [comment]
Fixed in #173
