### ISSUE TITLE
Look into removing SECURITY DEFINER from `delete_all_traces`

### ISSUE THREAD

**Issue by JamesGuthrie** [timescale/promscale_extension#136]
In https://github.com/timescale/promscale_extension/pull/132 we marked `ps_trace.delete_all_traces()` as `SECURITY DEFINER`. Technically this shouldn't be necessary, as long as the `prom_admin` user has `TRUNCATE` on the underlying tables.

Unfortunately this exposed an issue in how TimescaleDB handles this: https://github.com/timescale/timescaledb/issues/4183

**Comment by jgpruitt** [comment]
Actually, it may be better to leave this as security definer. We may not want to hand out TRUNCATE to anyone and only let it be executed via this function.

**Comment by JamesGuthrie** [comment]
Ya that makes sense. I will close this.
