### ISSUE TITLE
Make superuser owner of metric tables and views

### ISSUE THREAD

**Issue by JamesGuthrie** [timescale/promscale_extension#138]
In https://github.com/timescale/promscale_extension/pull/132 we made `prom_modifier` the owner of dynamically created metric tables.

As noted in https://github.com/timescale/promscale_extension/pull/132/files#r829247484, this breaks other things. We need to remove the `ALTER OWNER` on tables and views, and fix some functions (by making them security definer).

In particular, the following four lines must go:

```
EXECUTE format('ALTER TABLE %I.%I OWNER TO prom_modifier', NEW.table_schema, NEW.table_name);
EXECUTE format('ALTER TABLE prom_data_series.%1$I OWNER TO prom_modifier', NEW.table_name);
EXECUTE FORMAT('ALTER VIEW prom_series.%1$I OWNER TO prom_modifier', view_name);
EXECUTE FORMAT('ALTER VIEW prom_metric.%1$I OWNER TO prom_modifier', table_name);
```

**Comment by cevian** [comment]
Fixed in #173
