### ISSUE TITLE
Build fails on Ubuntu 18.04 due to pgx

### ISSUE THREAD

**Issue by rudimk** [timescale/promscale_extension#16]
I'm trying to build this extension on a fresh Ubuntu 18.04 machine, where I've just installed Postgres 13 and TimescaleDB. Running `make` results in the following error:

```
ubuntu@telemetry-sandbox:~/promscale_extension$ make
Makefile:58: warning: overriding recipe for target 'clean'
/usr/lib/postgresql/13/lib/pgxs/src/makefiles/pgxs.mk:355: warning: ignoring old recipe for target 'clean'
awk: warning: escape sequence `\.' treated as plain `.'
cargo build --release --features pg13
   Compiling pgx-pg-sys v0.1.19 (https://github.com/JLockerman/pgx.git?branch=guardless#c8248249)
error: failed to run custom build command for `pgx-pg-sys v0.1.19 (https://github.com/JLockerman/pgx.git?branch=guardless#c8248249)`

Caused by:
  process didn't exit successfully: `/home/ubuntu/promscale_extension/target/release/build/pgx-pg-sys-3127bd65715148b6/build-script-build` (exit status: 1)
  --- stderr
  manifest_dir=/home/ubuntu/.cargo/git/checkouts/pgx-24f98968818058e4/c824824/pgx-pg-sys
  shim_dir=/home/ubuntu/.cargo/git/checkouts/pgx-24f98968818058e4/c824824/pgx-pg-sys/cshim
  Error: Custom { kind: NotFound, error: "/home/ubuntu/.pgx/config.toml not found.  Have you run `cargo pgx init` yet?" }
Makefile:55: recipe for target 'target/release/libpromscale_rs.a' failed
make: *** [target/release/libpromscale_rs.a] Error 101
```

Then I ran `cargo pgx init` which too, fails:

```
ubuntu@telemetry-sandbox:~$ cargo pgx init
error: no such subcommand: `pgx`

	Did you mean `fix`?
```

A quick Google search threw up this other [issue](https://github.com/zombodb/pgx/issues/151), where apparently a workaround is to set the `BINDGEN_EXTRA_CLANG_ARGS` environment variable, and then running `cargo pgx init` - I'm assuming running that will help the build proceed. But the referenced issue was on a Mac, and I'm a little unsure about how I should adapt `BINDGEN_EXTRA_CLANG_ARGS` for Ubuntu. 

My apologies if this was an elementary question :)

**Comment by grawlinson** [comment]
Any update on this? This is blocking usage of the package on Arch Linux.

**Comment by cevian** [comment]
We've updated the installation section https://github.com/timescale/promscale_extension#installation 

I think you need to run 
```
cargo install --git https://github.com/JLockerman/pgx.git --branch timescale cargo-pgx && cargo pgx init
```

**Comment by grawlinson** [comment]
I maintain the [AUR](https://aur.archlinux.org/packages/promscale/) package of promscale_extension, and that's simply adding an unnecessary dependency.

```
warning: be sure to add `/build/.cargo/bin` to your PATH to be able to run the installed binaries
  Discovered Postgres v13.3, v12.7, v11.12, v10.17
 Downloading Postgres v11.12 from https://ftp.postgresql.org/pub/source/v11.12/postgresql-11.12.tar.bz2
 Downloading Postgres v13.3 from https://ftp.postgresql.org/pub/source/v13.3/postgresql-13.3.tar.bz2
 Downloading Postgres v10.17 from https://ftp.postgresql.org/pub/source/v10.17/postgresql-10.17.tar.bz2
 Downloading Postgres v12.7 from https://ftp.postgresql.org/pub/source/v12.7/postgresql-12.7.tar.bz2
```

What's this? I already have postgresql installed.

**Comment by cevian** [comment]
@grawlinson ahh sorry for the confusion if you already have PG installed you can do `cargo pgx init --pg13=</path/to/pg_config>` for pg13 or --pg12 etc. Please see https://github.com/zombodb/pgx/blob/master/cargo-pgx/README.md.  PGX is a development library that allows cross-version development of rust-based Postgres extensions.

**Comment by grawlinson** [comment]
Thank you, I’ll have a play around and get back to you. 👍

**Comment by rudimk** [comment]
Glad it's working for you, @grawlinson!

Many thanks for the tips, @cevian - I'm afraid it still doesn't work. But this time it doesn't seem to be anything but a permissions problem with `cargo`:

```
ubuntu@terraform-sandbox:~$ cargo pgx init --pg13=/etc/postgresql/13/main/postgresql.conf
  Discovered Postgres v13.3, v12.7, v11.12, v10.17
  Validating /etc/postgresql/13/main/postgresql.conf
     [error] : Permission denied (os error 13)
```

Interesting. Obviously I decided to do the obvious:

```
ubuntu@terraform-sandbox:~$ sudo /home/ubuntu/.cargo/bin/cargo pgx init --pg13=/etc/postgresql/13/main/postgresql.conf
  Discovered Postgres v13.3, v12.7, v11.12, v10.17
  Validating /etc/postgresql/13/main/postgresql.conf
     [error] : Permission denied (os error 13)
```

Sometimes the obvious is useless haha. While I haven't yet figured this out, I'm thinking I'll try and see if I can install the Rust toolchain _outside_ the current user's directory, which might mean not using `rustup`. I'll play with this a little more and let you know what happens. But as far as I can see - this isn't an issue with promscale, just another little hiccup with the entire toolchain.

Thanks once again!

**Comment by cevian** [comment]
@rudimk the argument to `--pg13` should _not_ be the config file but rather the `pg_config` binary that comes with PostgreSQL.

**Comment by ramonguiu** [comment]
@rudimk I'm closing this issue since we believe we provided the instructions to address it. If the issue still persists, please reopen it.
