### ISSUE TITLE
Public facing documentation for Tracing.

### ISSUE THREAD

**Issue by sumerman** [timescale/promscale_extension#161]
We want to provide documentation about how to query trace data in docs.timescale.com on its own page:  Promscale / Query data in Promscale / Query trace data with SQL. The content in the "Query metric data with SQL" in fQuery data in Promscale  will go under Promscale / Query data in Promscale / Query metric data with SQL, and  Promscale / Query data in Promscale will contain the index page with the intro section that currently lives in Promscale / Query data in Promscale. The documentation for querying traces should include:
1. A description of the span, event and link views.
2. Examples of SQL queries: top 20 slowest traces, a timeseries with the request rate, a timeseries with latency, the most common errors in spans.
Those are available  the [APM Grafana dashboards](https://github.com/timescale/promscale/tree/master/docs/mixin/dashboards) and in the [tracing GA blog post](https://www.timescale.com/blog/observability-powered-by-sql-understand-your-systems-like-never-before-with-opentelemetry-traces-and-postgresql/)
3. Specific documentation about how to use resource and span tags in the SELECT, WHERE, JOINS, GROUP BY and ORDER BY.

Similar to what https://docs.timescale.com/promscale/latest/query-data/#query-metric-data-with-sql covers for metrics. could be a good starting point.

**Comment by pgnickb** [comment]
As I didn't have a chance to dive deeper into the system during the GA dev cycle I decided to use this opportunity to research relevant topics and get a better overview of our code base (both `timescale` and `promscale`). This hindered the progress on the docs for obvious reasons.

Below is a TOC of the upcoming doc and status of each chapter. Missing :heavy_check_mark: means it's not done, not that there is literally no content.

**Querying trace data**
1. Trace data structure 

- [ ] 1.1. Single span
- [ ] 1.2. Views
- [ ] 1.2.1. `span` view
- [ ] 1.2.2. `event` view
- [ ] 1.2.3. `link` view

2. Example of SQL queries

- [ ] 2.1. Top 20 slowest traces
- [ ] 2.2. Timeseries with the request rate
- [ ] 2.3. Timeseries with latency
- [ ] 2.4. Most common errors in spans

3. Querying resource and span tags

- [ ] 3.1. Simple queries
- [ ] 3.2. Filtering
- [ ] 3.3. Joins
- [ ] 3.4. Grouping
- [ ] 3.5. Sorting

**Comment by ramonguiu** [comment]
I have done my review and updates and now is waiting on the docs team to complete the work
