### ISSUE TITLE
Build fails on FreeBSD13

### ISSUE THREAD

**Issue by devosalain** [timescale/promscale_extension#21]
I use rust-1.53.0,
postgresql12-server-12.7_1
It would be interesting to know the minimum requirements towards rust-versions & postgresql-server versions.
Part of my error log,
Compiling time-macros v0.1.1
   Compiling thiserror v1.0.25
   Compiling serde-xml-rs v0.4.1
   Compiling toml v0.5.8
   Compiling serde_cbor v0.11.1
   Compiling bincode v1.3.3
   Compiling pgx-utils v0.1.19 (https://github.com/JLockerman/pgx.git?branch=guardless#c8248249)
   Compiling pgx-pg-sys v0.1.19 (https://github.com/JLockerman/pgx.git?branch=guardless#c8248249)
   Compiling pgx-macros v0.1.19 (https://github.com/JLockerman/pgx.git?branch=guardless#c8248249)
error: failed to run custom build command for `pgx-pg-sys v0.1.19 (https://github.com/JLockerman/pgx.git?branch=guardless#c8248249)`

Caused by:
  process didn't exit successfully: `/usr/home/x/promscale_extension/target/release/build/pgx-pg-sys-960e43f55619c8f5/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=/home/x/.pgx/config.toml
  cargo:rerun-if-changed=include/pg10.h
  cargo:rerun-if-changed=include/pg11.h
  cargo:rerun-if-changed=include/pg12.h
  cargo:rerun-if-changed=include/pg13.h
  cargo:rerun-if-changed=cshim/pgx-cshim.c
  cargo:rerun-if-changed=cshim/Makefile

  --- stderr
  manifest_dir=/home/x/.cargo/git/checkouts/pgx-24f98968818058e4/c824824/pgx-pg-sys
  shim_dir=/home/x/.cargo/git/checkouts/pgx-24f98968818058e4/c824824/pgx-pg-sys/cshim
  Generating bindings for pg12
  [[bindings_diff]] "rustfmt" "/usr/home/x/promscale_extension/target/release/build/pgx-pg-sys-7ab052ffa365188a/out/pg12.rs"
  [[bindings_diff]] -------- "rustfmt" "/usr/home/x/promscale_extension/target/release/build/pgx-pg-sys-7ab052ffa365188a/out/pg12.rs" -------- 
  [[bindings_diff]] /----------------------------------------

  [[bindings_diff]] "rustfmt" "/usr/home/x/promscale_extension/target/release/build/pgx-pg-sys-7ab052ffa365188a/out/pg12_oids.rs"
  [[bindings_diff]] -------- "rustfmt" "/usr/home/x/promscale_extension/target/release/build/pgx-pg-sys-7ab052ffa365188a/out/pg12_oids.rs" -------- 
  [[bindings_diff]] /----------------------------------------

  libpgx_cshim=/home/x/.cargo/git/checkouts/pgx-24f98968818058e4/c824824/pgx-pg-sys/cshim/libpgx-cshim-12.a
  PATH for build_shim=/usr/local/bin:/home/x/perl5/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/home/x/bin:/home/x/.local/bin:/home/x/.rvm/bin:/home/x/go/bin:/home/x/perl5/bin:/home/x/.cargo/bin
  shim_dir=/home/x/.cargo/git/checkouts/pgx-24f98968818058e4/c824824/pgx-pg-sys/cshim
  [shim for PG v12] "make" "clean" "libpgx-cshim-12.a"
  [shim for PG v12] -------- "make" "clean" "libpgx-cshim-12.a" -------- 
  [shim for PG v12] [stdout] 
  [shim for PG v12] [stdout] make: stopped in /usr/home/x/.cargo/git/checkouts/pgx-24f98968818058e4/c824824/pgx-pg-sys/cshim
  [shim for PG v12] [stderr] make: "/usr/home/x/.cargo/git/checkouts/pgx-24f98968818058e4/c824824/pgx-pg-sys/cshim/Makefile" line 20: Could not find 
  [shim for PG v12] [stderr] make: Fatal errors encountered -- cannot continue
  [shim for PG v12] /----------------------------------------

  thread 'main' panicked at 'failed to make pgx-cshim for v12', /home/x/.cargo/git/checkouts/pgx-24f98968818058e4/c824824/pgx-pg-sys/build.rs:529:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
gmake: *** [Makefile:55: target/release/libpromscale_rs.a] Error 101
HOST:x: /home/x/promscale_extension >

**Comment by devosalain** [comment]
I retried the build this time using postgresql13-server-13.3_1. The build failed also but rather late in the build process,
Compiling bincode v1.3.3
   Compiling serde-xml-rs v0.4.1
   Compiling toml v0.5.8
   Compiling pgx-utils v0.1.19 (https://github.com/JLockerman/pgx.git?branch=guardless#c8248249)
   Compiling pgx-pg-sys v0.1.19 (https://github.com/JLockerman/pgx.git?branch=guardless#c8248249)
   Compiling pgx-macros v0.1.19 (https://github.com/JLockerman/pgx.git?branch=guardless#c8248249)
error: failed to run custom build command for `pgx-pg-sys v0.1.19 (https://github.com/JLockerman/pgx.git?branch=guardless#c8248249)`

Caused by:
  process didn't exit successfully: `/usr/home/Services/promscale_extension_error/target/release/build/pgx-pg-sys-f85a41367381c3e1/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=/home/x/.pgx/config.toml
  cargo:rerun-if-changed=include/pg10.h
  cargo:rerun-if-changed=include/pg11.h
  cargo:rerun-if-changed=include/pg12.h
  cargo:rerun-if-changed=include/pg13.h
  cargo:rerun-if-changed=cshim/pgx-cshim.c
  cargo:rerun-if-changed=cshim/Makefile

  --- stderr
  manifest_dir=/home/x/.cargo/git/checkouts/pgx-24f98968818058e4/c824824/pgx-pg-sys
  shim_dir=/home/x/.cargo/git/checkouts/pgx-24f98968818058e4/c824824/pgx-pg-sys/cshim
  Generating bindings for pg13
  [[bindings_diff]] "rustfmt" "/usr/home/Services/promscale_extension_error/target/release/build/pgx-pg-sys-196fb5ce622ff3ab/out/pg13.rs"
  [[bindings_diff]] -------- "rustfmt" "/usr/home/Services/promscale_extension_error/target/release/build/pgx-pg-sys-196fb5ce622ff3ab/out/pg13.rs" -------- 
  [[bindings_diff]] /----------------------------------------

  [[bindings_diff]] "rustfmt" "/usr/home/Services/promscale_extension_error/target/release/build/pgx-pg-sys-196fb5ce622ff3ab/out/pg13_oids.rs"
  [[bindings_diff]] -------- "rustfmt" "/usr/home/Services/promscale_extension_error/target/release/build/pgx-pg-sys-196fb5ce622ff3ab/out/pg13_oids.rs" -------- 
  [[bindings_diff]] /----------------------------------------

  libpgx_cshim=/home/x/.cargo/git/checkouts/pgx-24f98968818058e4/c824824/pgx-pg-sys/cshim/libpgx-cshim-13.a
  PATH for build_shim=/usr/local/bin:/home/x/perl5/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/home/x/bin:/home/x/.local/bin:/home/x/.rvm/bin:/home/x/go/bin:/home/x/perl5/bin:/home/x/.cargo/bin
  shim_dir=/home/x/.cargo/git/checkouts/pgx-24f98968818058e4/c824824/pgx-pg-sys/cshim
  [shim for PG v13] "make" "clean" "libpgx-cshim-13.a"
  [shim for PG v13] -------- "make" "clean" "libpgx-cshim-13.a" -------- 
  [shim for PG v13] [stdout] 
  [shim for PG v13] [stdout] make: stopped in /usr/home/x/.cargo/git/checkouts/pgx-24f98968818058e4/c824824/pgx-pg-sys/cshim
  [shim for PG v13] [stderr] make: "/usr/home/x/.cargo/git/checkouts/pgx-24f98968818058e4/c824824/pgx-pg-sys/cshim/Makefile" line 20: Could not find 
  [shim for PG v13] [stderr] make: Fatal errors encountered -- cannot continue
  [shim for PG v13] /----------------------------------------

  thread 'main' panicked at 'failed to make pgx-cshim for v13', /home/x/.cargo/git/checkouts/pgx-24f98968818058e4/c824824/pgx-pg-sys/build.rs:529:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
gmake: *** [Makefile:55: target/release/libpromscale_rs.a] Error 101
HOST:x: /home/Services/promscale_extension_error >                    

My versions are,
rust-1.53.0                   
rust-bindgen-0.58.1_2       
rust-cbindgen-0.19.0_2

**Comment by cevian** [comment]
I believe this is because rustfmt is not installed

**Comment by devosalain** [comment]
As test i did,
cargo install --force rustfmt  
rustfmt -h
gmake clean
gmake
Same error ...

**Comment by ramonguiu** [comment]
We don't currently have plans to test and fix issues on FreeBSD. If you know how to fix the problem, we'd be happy to review a PR.

**Comment by feld** [comment]
For future reference we have a working port of this in FreeBSD's ports collections: https://www.freshports.org/databases/postgresql-promscale/
