### ISSUE TITLE
Add SQL functions to get default metric retention period and per metric retention period

### ISSUE THREAD

**Issue by ramonguiu** [timescale/promscale_extension#213]
Currently we provide the following functions to manage the retention period for metrics: `set_default_retention_period(retention_period)`,  `set_metric_retention_period(metric_name, retention_period)` and `reset_metric_retention_period(metric_name)`.

We should also provide the corresponding `get_default_retention_period()` and `get_metric_retention_period(metric_name)`.

**Comment by JamesGuthrie** [comment]
These functions already exist, but are in the private `_prom_catalog` schema.
