### ISSUE TITLE
Does not compile for PostgreSQL 14

### ISSUE THREAD

**Issue by grawlinson** [timescale/promscale_extension#23]
Will not compile due to `pgx` not supporting the latest version of PostgreSQL.

The same goes for timescaledb-toolkit.

**Comment by grawlinson** [comment]
It looks like pgx's next release (0.2.0) will include [support for PG14](https://github.com/zombodb/pgx/pull/245).

**Comment by JamesGuthrie** [comment]
@grawlinson we have release version `0.3.0` of the extension with PG14 support. We're working on a Promscale release which will be compatible with the extension, see https://github.com/timescale/promscale/issues/890.

If you compile and install version 0.3.0 of the extension and use it with current promscale it will probably work, but that's not really recommended.
