### ISSUE TITLE
Provide better upgrade instructions for 0.3.0 -> 0.5.0

### ISSUE THREAD

**Issue by JamesGuthrie** [timescale/promscale_extension#270]
The following issues have cropped up recently with users wanting to upgrade from a previous version to the current version:

- When using the extension compiled from source, users are not sure how they should upgrade to 0.5.0 (e.g. can they just use the distro packages? When can/can't they?). ([link to community slack](https://timescaledb.slack.com/archives/C011FC0PPC5/p1652775715500199))
- Upgrade requires adjusting `max_locks_per_transaction` to succeed https://github.com/timescale/promscale_extension/issues/274#issuecomment-1132921038
- Upgrade takes a lot longer than expected (~1hr) (https://github.com/timescale/promscale_extension/issues/274#issuecomment-1132921038)
  - #291 

Beyond documenting it, can we make the upgrade process also faster / easier for the user somehow?

**Comment by JamesGuthrie** [comment]
# Tuning `max_locks_per_transaction`

Upgrading from a previous version of Promscale to 0.11.0 requires taking a lock on a large number of tables. If Postgres has not been correctly configured for this, the process may fail with the following error:

```
promscale: level=error ts=2022-05-19T17:00:00.100Z caller=runner.go:116 msg="aborting startup due to error" err="migration error: error while installing promscale extension version 0.0.0: error installing Promscale extension at version 0.0.0: ERROR: out of shared memory (SQLSTATE 53200)"
```

## Background

This error arises because postgres has a limited amount of shared memory available to store locks on objects. The size of this memory is `max_locks_per_transaction` * (`max_connections` + `max_prepared_transactions`). By increasing `max_locks_per_transaction`, one can increase the amount of shared memory available to all connections.

Unfortunately, the number of locks which will be taken is not fixed, but is proportional to the number of metrics ingested, and the time period for which those metrics are stored (in timescale parlance, the number of hypertables and chunks).

The following query will provide an _upper bound_ for the number of objects which will be locked by the upgrade process:

```SQL
SELECT 400 + count(*) AS locked_object_count
    FROM pg_class
    JOIN pg_namespace n ON n.oid = pg_class.relnamespace
    WHERE
          n.nspname <> 'pg_catalog'
      AND n.nspname !~ '^pg_toast'
      AND n.nspname <> 'information_schema'
;
```

## Mitigation

Determine the new minimum value for `max_locks_per_transaction`, and configure this value in your `postgresql.conf`:

```SQL
WITH max_objects_touched AS (
        SELECT 400 + count(*) as max_objects_touched
        FROM pg_class
                 JOIN pg_namespace n ON n.oid = pg_class.relnamespace
        WHERE n.nspname <> 'pg_catalog'
          AND n.nspname !~ '^pg_toast'
          AND n.nspname <> 'information_schema'
    ),
    max_conns AS (
        SELECT SUM(setting::INTEGER) as max_conns FROM pg_settings WHERE name IN ('max_connections', 'max_prepared_transactions')
    )
SELECT max_objects_touched/max_conns AS max_locks_per_transaction FROM max_objects_touched, max_conns;
```

Note: This assumes that the promscale upgrade process is the only process connected to the database cluster. Should this not be the case, you may need to provide some additional headroom by increasing the suggested value of `max_locks_per_transaction`.

**Comment by niksajakovljevic** [comment]
Overall looks good. 
I am wondering we might need to safeguard this number: eg if `max_locks_per_transaction` is big enough that it can't fit into shared memory?  I guess a DB server will not be able to start in that case
I also wonder what is the current value for `max_locks_per_transaction` and if we should tweak it to some more reasonable value to avoid this appearing (at least for majority of users)?

**Comment by jgpruitt** [comment]
Is it possible to compute how many locks we are likely to need? If so, we could check that the `max_locks_per_transaction` setting is high enough first thing in the upgrade, and abort with an appropriate log message if it is not set high enough.

**Comment by pgnickb** [comment]
@jgpruitt  yeah we're already kinda doing the calculation. We can use some rough comparison and throw warnings/errors if the estimate is significantly higher than the current setting. I'd say if we estimate to use >50% of available locks its an info, 75% is a warning and we can safely error if the estimate is above the current value.

**Comment by JamesGuthrie** [comment]
I've opened a PR in the docs repo: https://github.com/timescale/docs/pull/1136

**Comment by JamesGuthrie** [comment]
This was merged in the docs repo
