### ISSUE TITLE
Improve how promscale's e2e tests are run against this codebase

### ISSUE THREAD

**Issue by JamesGuthrie** [timescale/promscale_extension#277]
The promscale codebase has broad end-to-end test case coverage. A lot of those tests should probably be run against this repository directly. Instead, we must trigger a test run in the promscale repo to run the end-to-end tests against this codebase.

We should have a mechanism to integrate running those tests directly in the CI of this repository.

**Comment by sumerman** [comment]
- https://github.com/timescale/promscale/pull/1402
- https://github.com/timescale/promscale_extension/pull/327
