### ISSUE TITLE
Implement upgrade tests

### ISSUE THREAD

**Issue by JamesGuthrie** [timescale/promscale_extension#278]
Upgrade tests provide a lot of value in ensuring that the clean install path and upgrade path result in the same SQL schema. These tests are completely missing in the extension codebase. The upgrade tests on the Promscale Connector side do not adequately cover this, as they may arbitrarily skip over versions.

Somewhat related to #277.

**Comment by JamesGuthrie** [comment]
Some implementation notes:

- Initially we want to keep these in Docker, despite a push to enable local (non-Docker) testing.
- We should setup these tests in a "docker-only" workspace, for tests which require docker.
- The existing dump-restore would also go into that workspace.

**Comment by jgpruitt** [comment]
Progress so far: 

A "quick and dirty" version of the upgrade tests has been merged. It has some duplicate code and only uses a single docker image.
https://github.com/timescale/promscale_extension/pull/410

The PostgresTestHarness has been improved to allow tests to specify the docker image they want to use.
https://github.com/timescale/promscale_extension/pull/425

Next, I plan to improve the upgrade tests to use the "latest" docker image for the "prior" version of the extension and the "local" (by default) docker image for the "current" version. I also plan to clean up the code and move duplicate code to a shared module.

**Comment by JamesGuthrie** [comment]
The finalized version of this was merged in https://github.com/timescale/promscale_extension/pull/451.
