### ISSUE TITLE
Error raised while dropping already dropped metric

### ISSUE THREAD

**Issue by mjf** [timescale/promscale_extension#293]
I am getting
```sql
ERROR:  null values cannot be formatted as an SQL identifier
CONTEXT:  PL/pgSQL function drop_metric(text) line 12 at EXECUTE
```
if I call `prom_api.drop_metric()` on already dropped metric. I am not sure if it is intentional to produce an error in this case. It does not seem to be critical issue, I am just wondering if it is correct.

**Comment by jgpruitt** [comment]
https://github.com/timescale/promscale_extension/pull/152#issuecomment-1085128596

This issue has been fixed.
