### ISSUE TITLE
Upgrade to 0.5.0 breaks because `prom_schema_migrations` table in unexpected schema

### ISSUE THREAD

**Issue by JamesGuthrie** [timescale/promscale_extension#371]
The `prom_schema_migrations` table was created (and used by) Promscale to keep track of the schema version installed by Promscale in the database.

In the migration to having all objects become extension-owned (Promscale 0.11.0, extension 0.5.0), we used the `prom_schema_migrations` table as a marker to know if we were on the upgrade path, or the fresh-install path.

This required coordination between the Promscale Connector, and the Promscale extension. The connector checked if the table was present, and triggered the "extension takeover" process (drop old extension, install extension at 0.0.0, upgrade extension to newest version). The extension takeover process would drop the table `public.prom_schema_migrations` to indicate that the upgrade process was complete.

Unfortunately, the original creation of the `prom_schema_migrations` table _was not_ schema qualified. This means that the schema that the table ends up in is dependent on the user's `search_path`. This can cause the upgrade to fail.

**Comment by ramonguiu** [comment]
@JamesGuthrie , in practical terms what % of users would you expect to actually be impacted by this? Most users, just a handful doing some custom installation?
Since the Promscale Connector was responsible for creating that table on fresh install, were we setting the search_path at that point and so in theory no user should be impacted?

**Comment by JamesGuthrie** [comment]
This was fixed in the extension in https://github.com/timescale/promscale_extension/pull/372, and in the connector in https://github.com/timescale/promscale/pull/1452.
