### ISSUE TITLE
Write design document for better out-of-the-box default settings

### ISSUE THREAD

**Issue by ramonguiu** [timescale/promscale_extension#378]
[Design doc](https://docs.google.com/document/d/1S7c1JhlqYElDdywomSTFGFriNta6V4Kr_R14V_Kso9M/edit)

**Comment by VineethReddy02** [comment]
FYI, we have a [doc](https://docs.google.com/document/d/1Bjw9dHiryyzLJkRuZJnT1t4Nx14ucDdAafJsJoKScLU/edit?usp=sharing) that is put together while helping the user tune ingestion. Can help as a reference for better OOB defaults.
