### ISSUE TITLE
Run timescaledb-tune in the docker image in Promscale mode

### ISSUE THREAD

**Issue by ssola** [timescale/promscale_extension#432]

**Comment by jgpruitt** [comment]
This cannot be done "automatically" unless we publish our own promscale-specific docker images, and we don't want to tackle that right now. We'll update the documentation to tell people how to run the HA image with timescaledb-tune using the `promscale` profile.

We do need to get Cloud to expose this option in the UI -- "I want this cloud instance to be a promscale instance".
