### ISSUE TITLE
WARNING:  01000: Checksum of migration "001-extension.sql" has changed

### ISSUE THREAD

**Issue by jgpruitt** [timescale/promscale_extension#438]
The 001-extension.sql incremental script actually has to change because we have to change the version of the .so to which the functions point. However, being an incremental script, it is wrapped in the wrapper that checks the migration table and raises a warning if the script has changed.

Thus, you get this warning when updating from one version of the extension to the next, but this is expected behavior.

**Comment by pgnickb** [comment]
It's addressed in post-release PR I think

**Comment by jgpruitt** [comment]
I see that the docs on how to release say:
```
Update the extension version in `Cargo.toml`, don't forget to fix the `.so` references in `incremental/001-extension.sql`, `idempotent/014-extension-type-functions.sql`, and `promscale--0.0.0.sql`.
```
But that doesn't make the warning go away. Unless, I'm mistaken
