### ISSUE TITLE
How to build from source on FreeBSD ?

### ISSUE THREAD

**Issue by devosalain** [timescale/promscale_extension#457]
Promscale was working fine , that is until the new requirement promscale_postgresql_database_extension,
Log:
```
level=warn ts=2022-08-02T02:03:40.978Z caller=new_migrate.go:129 msg="as of Promscale version 0.11.0, the Promscale database extension is mandatory. please install the latest version of this extension in your TimescaleDB/PostgreSQL database in order to proceed."
level=error ts=2022-08-02T02:03:40.979Z caller=runner.go:116 msg="aborting startup due to error" err="migration error: error while checking for supported and available promscale extension versions: the extension is not available"
```
How do i build this extension from source on FreeBSD ?

**Comment by JamesGuthrie** [comment]
Hi @devosalain, unfortunately we don't have installation instructions for any of the BSDs. We just don't have the experience (or, until now, need).

You should be able to follow the installation instructions for Ubuntu with some success. It being BSD, you may need to make some compromises/hacks.

I have no BSD experience, but was able to get the promscale_extension to compile by doing the following things:
- Install postgres with `pkg`
- Install `gmake` and replace system `make` with `gmake` (hacky, but necessary - apparently both our Makefile and other upstream Makefiles use non-POSIX gnu make extensions)
- Run `BINDGEN_EXTRA_CLANG_ARGS=-I/usr/local/include/ make package`

I wish you the best of luck.

**Comment by JamesGuthrie** [comment]
I'm going to close this issue as I believe that I've answered it, and didn't hear anything back. If there are any further questions, feel free to reopen.
