### ISSUE TITLE
Understand safe versioning of the shared object binary

### ISSUE THREAD

**Issue by JamesGuthrie** [timescale/promscale_extension#46]
Currently we do not have a solid understanding of how ABI changes in the shared object can be handled in the extension.

We would like to first build up (and document) the knowledge to understand how ABI changes impact the installed extension.
With that knowledge, we will plan how to account for ABI changes in our extension.

**Comment by cevian** [comment]
@JamesGuthrie can this be close?

**Comment by cevian** [comment]
Closing because I think it's done and falls under the https://github.com/timescale/promscale_extension/issues/126 umbrella
