### ISSUE TITLE
Clean up extension internals to make better use of pgx types and facilities

### ISSUE THREAD

**Issue by bitwalker** [timescale/promscale_extension#48]
There are a few areas which could use some refactoring to make future changes easier and safer:

- [x] Implement `Allocator` API (via nightly) on top of Postgres MemoryContexts for the types of contexts the extension is used in
- [ ] Remove `Inner<T>` type and use `Box<T, A>` and `Vec<T, A>` on top of custom allocators
- [ ] Remove redundant wrapper types for things which have appropriate implementations already in pgx (`bytea`, `TimestampTz`)

We may want/need to upstream some or all of the first two items in the list, e.g. to allow using `alloc` types which are parameterized on the `Allocator` type to be used as arguments in function signatures. We should be able to proceed without that from what I've observed, but it would allow for a cleaner integration, and open the door to optimizations such as avoiding unnecessary copies when using `Box` or `Vec` as result types.

There are PRs coming for all of the above today/tomorrow which we can use to discuss the changes outlined above.

**Comment by JamesGuthrie** [comment]
I think that all of these points will be covered when we start using PGX's aggregate support: https://github.com/timescale/promscale_extension/pull/62. I would suggest closing this.
