### ISSUE TITLE
make package throws --force-create-or-replace argument issue 

### ISSUE THREAD

**Issue by cyapa** [timescale/promscale_extension#484]
Hello,

In  **0.6.0** tag source code when I try to run `make package` it throws an error at the line number 99: 
`cargo pgx schema pg${PG_BUILD_VERSION} --force-create-or-replace --release >/dev/null`

![image](https://user-images.githubusercontent.com/20187382/186895951-ef511a6e-5178-40af-929d-154c28ca7dc5.png)

I have Rust compiler installed. What could cause this? :thinking: 

Ran on : Ubuntu 20.04.5 LTS

Thanks! :pray:

**Comment by sumerman** [comment]
Hi @cyapa. How did you install pgx?

**Comment by cyapa** [comment]
> Hi @cyapa. How did you install pgx?

Hi, I used `$ cargo install cargo-pgx`

**Comment by sumerman** [comment]
I see. We rely on our own fork of pgx. Please, use the `install-cargo-pgx.sh` script from this repository.

**Comment by cyapa** [comment]
> I see. We rely on our own fork of pgx. Please, use the `install-cargo-pgx.sh` script from this repository.

Thank you so much for the very fast replies! I got it working :heart:
