### ISSUE TITLE
Could not access file \"$libdir/promscale-0.5.4\ when running promscale connection command

### ISSUE THREAD

**Issue by cyapa** [timescale/promscale_extension#485]
Hello all,

A newbie to Prometheus, Promscale, Promscale extenstion & TimescalDB here.

I have a running Prometheus agent and a timescale DB configured on my postgreSQL 14 instance. Also installed the Promscale extension successfully.

When I downloaded the latest release of Promscale and run `./promscale --db.name promscale --db.password ***** --db.ssl-mode allow`

It gives me the error:

```
level=warn ts=2022-08-29T06:56:11.123Z caller=extension.go:57 msg="could not install promscale: ERROR: could not access file \"$libdir/promscale-0.5.4\": No such file or directory (SQLSTATE 58P01). continuing without extension"
level=error ts=2022-08-29T06:56:11.128Z caller=runner.go:116 msg="aborting startup due to error" err="migration error: failed to install/upgrade promscale extension: error encountered while migrating extension: problem checking promscale extension version: promscale extension is required but is not installed"
```

![image](https://user-images.githubusercontent.com/20187382/187141549-59b779fb-20d1-4f92-9680-132982cbe06b.png)

Any idea on what caused this? :)

**Comment by JamesGuthrie** [comment]
Hi @cyapa I suspect that you have installed extension version 0.6.0, which was just tagged last week. Promscale 0.13.0 does not support extension version 0.6.0 yet. Please install extension version 0.5.4.

**Comment by cyapa** [comment]
> Hi @cyapa I suspect that you have installed extension version 0.6.0, which was just tagged last week. Promscale 0.13.0 does not support extension version 0.6.0 yet. Please install extension version 0.5.4.

Thanks @JamesGuthrie Yeah I installed the 0.6.0 version. I will revert it to 0.5.4 :+1: 

Thank you!

**Comment by cyapa** [comment]
Hi @JamesGuthrie 
So I reverted the Promscale version to 0.5.4 ( queried from postresql) 
![image](https://user-images.githubusercontent.com/20187382/187158660-1d9f5071-9752-4a15-84a5-6d81ddd9d9a9.png)


And I re-ran the promscale command on the version 0.13.0

Still getting the same
./promscale --db.name promscale --db.password promscale --db.user promscale --db.ssl-mode allow --startup.install-extensions
2022/08/29 11:22:52 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
level=info ts=2022-08-29T08:22:52.385Z caller=runner.go:75 msg="Version: 0.13.0, Commit Hash: e7745aa1b95ac4d58f18beef9d06924062f5ee4c, Branch: HEAD"
level=info ts=2022-08-29T08:22:52.385Z caller=runner.go:80 config="{ListenAddr::9201 ThanosStoreAPIListenAddr: OTLPGRPCListenAddr::9202 PgmodelCfg:{CacheConfig:{SeriesCacheInitialSize:250000 seriesCacheMemoryMaxFlag:{kind:0 value:50} SeriesCacheMemoryMaxBytes:6596911104 MetricsCacheSize:10000 LabelsCacheSize:100000 ExemplarKeyPosCacheSize:10000 InvertedLabelsCacheSize:500000} AppName:promscale@0.13.0 Host:localhost Port:5432 User:promscale Password:**** Database:promscale SslMode:allow DbConnectionTimeout:1m0s IgnoreCompressedChunks:false AsyncAcks:false WriteConnections:0 WriterPoolSize:-1 ReaderPoolSize:-1 MaxConnections:-1 UsesHA:false DbUri:**** EnableStatementsCache:true} LogCfg:{Level:info Format:logfmt} TracerCfg:{OtelCollectorEndpoint: OtelCollectorTLSCertFile: OtelCollectorTLSKeyFile: JaegerCollectorEndpoint: SamplingRatio:1} APICfg:{AllowedOrigin:^(?:.*)$ ReadOnly:false HighAvailability:false AdminAPIEnabled:false TelemetryPath:/metrics Auth:0xc000239450 MultiTenancy:<nil> Rules:<nil>} LimitsCfg:{targetMemoryFlag:{kind:0 value:80} TargetMemoryBytes:13193822208} TenancyCfg:{SkipTenantValidation:false EnableMultiTenancy:false AllowNonMTWrites:false ValidTenantsStr:allow-all ValidTenantsList:[]} PromQLCfg:{EnabledFeatureMap:map[] PromscaleEnabledFeatureList:[] MaxQueryTimeout:2m0s SubQueryStepInterval:1m0s LookBackDelta:5m0s MaxSamples:50000000 MaxPointsPerTs:11000} RulesCfg:{NotificationQueueCapacity:10000 OutageTolerance:1h0m0s ForGracePeriod:10m0s ResendDelay:1m0s PrometheusConfigAddress: PrometheusConfig:global:\n  scrape_interval: 1m\n  scrape_timeout: 10s\n  evaluation_interval: 1m\n} TracingCfg:{MaxTraceDuration:1h0m0s} ConfigFile:config.yml DatasetConfig: TLSCertFile: TLSKeyFile: ThroughputInterval:1s Migrate:true StopAfterMigrate:false UseVersionLease:true InstallExtensions:true UpgradeExtensions:true UpgradePrereleaseExtensions:false StartupOnly:false}"
level=warn ts=2022-08-29T08:22:52.430Z caller=extension.go:57 msg="could not install promscale: ERROR: could not access file \"$libdir/promscale-0.5.4\": No such file or directory (SQLSTATE 58P01). continuing without extension"
level=error ts=2022-08-29T08:22:52.434Z caller=runner.go:116 msg="aborting startup due to error" err="migration error: failed to install/upgrade promscale extension: error encountered while migrating extension: problem checking promscale extension version: promscale extension is required but is not installed"

**Comment by JamesGuthrie** [comment]
@cyapa How did you install the extension into the filesystem? Did you compile from source, or install from our package repository?

I think that you will need to either recompile at 0.5.4, or install the package@0.5.4.

**Comment by cyapa** [comment]
> @cyapa How did you install the extension into the filesystem? Did you compile from source, or install from our package repository?
> 
> I think that you will need to either recompile at 0.5.4, or install the package@0.5.4.

I recompiled from source
`
git clone https://github.com/timescale/promscale_extension
cd promscale_extension
git checkout 0.5.4
make package
sudo make install
`

**Comment by JamesGuthrie** [comment]
Can you provide the output of the following command: `find $(pg_config --pkglibdir) -name 'promscale*.so'`

**Comment by cyapa** [comment]
> find $(pg_config --pkglibdir) -name 'promscale*.so'

![image](https://user-images.githubusercontent.com/20187382/187177087-6476755b-0a71-4034-be3a-7b5c9deda5ce.png)
 :grimacing: seems i still have the 0.6.0 running?

**Comment by JamesGuthrie** [comment]
Indeed. It seems like it. I'm not sure why though... I'm trying to reproduce this now.

**Comment by cyapa** [comment]
> Indeed. It seems like it. I'm not sure why though... I'm trying to reproduce this now.

Thank you! :pray: 
Let me know how it goes and how I can revert to 0.5.4 :)

**Comment by JamesGuthrie** [comment]
I just tried reproducing this. Are you sure that your invocation of `make package` was successful after `git checkout 0.5.4`? On my system I had to run `cargo install cargo-pgx --git https://github.com/timescale/pgx --branch promscale-staging` in order to install `cargo-pgx` at the correct version. Only then did `make package` work correctly, and it produced `target/release/promscale-pg14/usr/lib/postgresql/14/lib/promscale-0.5.4.so`.

**Comment by cyapa** [comment]
> I just tried reproducing this. Are you sure that your invocation of `make package` was successful after `git checkout 0.5.4`? On my system I had to run `cargo install cargo-pgx --git https://github.com/timescale/pgx --branch promscale-staging` in order to install `cargo-pgx` at the correct version. Only then did `make package` work correctly, and it produced `target/release/promscale-pg14/usr/lib/postgresql/14/lib/promscale-0.5.4.so`.

Actually for 0.5.4's `make build` I had to change pgx version in `Cargo.toml`. But then again, after the command, it creates a so file `target/release/promscale-pg14/usr/lib/postgresql/14/lib/promscale.so`  without the proper version number. 

I followed your steps and was able to generate a `promscale-0.5.4.so` :+1: Now my prometheus agent is successfully connected to a timescale DB. Thank you for assisting me @JamesGuthrie  :partying_face:
