### ISSUE TITLE
pg_dump and pg_restore not possible with promscale extension

### ISSUE THREAD

**Issue by tylerfontaine** [timescale/promscale_extension#5]
With the promscale extension installed, doing a backup and restore fails. Well, more precisely, the backup is fine, but the restore fails.

When you do the restore, it tries to create the promscale extension, which is explicitly blocked:

```
pg_restore version: pg_restore (PostgreSQL) 12.4
pg_restore: connecting to database for restore
pg_restore: creating SCHEMA "_prom_catalog"
pg_restore: creating SCHEMA "_prom_ext"
pg_restore: creating EXTENSION "timescaledb"
pg_restore: creating SCHEMA "prom_api"
pg_restore: creating SCHEMA "prom_data"
pg_restore: creating SCHEMA "prom_data_series"
pg_restore: creating SCHEMA "prom_info"
pg_restore: creating SCHEMA "prom_metric"
pg_restore: creating SCHEMA "prom_series"
pg_restore: creating EXTENSION "promscale"
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 3; 3079 8649789 EXTENSION promscale (no owner)
pg_restore: error: could not execute query: ERROR:  could not determine the version of the Promscale connector that was installed due to: relation "public.prom_schema_migrations" does not exist
HINT:  This extension should not be created manually. It will be created by the Promscale connector and requires the connector to be installed first.
CONTEXT:  PL/pgSQL function inline_code_block line 12 at RAISE
Command was: CREATE EXTENSION IF NOT EXISTS promscale WITH SCHEMA _prom_ext;
2020/10/21 16:52:54 pg_restore run failed in pre-data section: cmd.Run() failed with 'exit status 1'
```

Backup options used: 
`time pg_dump --format=directory --file ./backup -h ts.tsdb.tylerfontaine.me -U postgres -p 5432 prometheus -v`

So this leaves the user in an awkward position who would try to backup/restore the promscale data. It does work if you drop the extension before taking the backup, but that's less than ideal.

Seems like we should have either some instructions on backup/restore of promscale data or rethink the block on installing the extension manually when the migration data is missing.

**Comment by ramonguiu** [comment]
@cevian do you know if this is still a problem?

**Comment by JamesGuthrie** [comment]
This should be possible now, but we don't have any documentation for it. I've opened 749cf0d3d3ca3364cfe1a372059ea864042f2742
