### ISSUE TITLE
Non-metric tables in prom_data cause upgrade failure

### ISSUE THREAD

**Issue by jgpruitt** [timescale/promscale_extension#519]
In the 0.0.0 script, we transfer ownership of metric tables in the prom_data schema to the prom_admin role. 
https://github.com/timescale/promscale_extension/blob/master/templates/promscale--0.0.0.sql#L397

Later in the script, we check that all objects depending upon the extension are owned by the right user:
https://github.com/timescale/promscale_extension/blob/master/templates/promscale--0.0.0.sql#L551

We had a customer who had tables in the prom_data schema that were not referenced in the metric table, so the ownership transfer didn't happen, but the security check caught them and bailed out of the install.

These tables may be caggs, or maybe just random manually created tables. I think we need to either exclude them from the security check, or add a step to find them and transfer ownership.

**Comment by JamesGuthrie** [comment]
This was fixed in https://github.com/timescale/promscale_extension/pull/524
