### ISSUE TITLE
Mark Extension as Trusted

### ISSUE THREAD

**Issue by JamesGuthrie** [timescale/promscale_extension#54]
As part of the ongoing extension refactoring we would like to mark the extension as trusted. This will allow us to install the promscale extension without promscale having a superuser DB connection. Until now this was possible using [pgextwlist](https://github.com/dimitri/pgextwlist), but from PG13 onwards, extensions can be marked as trusted, and we can make things simpler for our end users.

In principle this is simply adding `trusted = true` to the `.control` file. There are wider-reaching security considerations which must be made about all SQL which is loaded as part of the extension: https://www.postgresql.org/docs/current/extend-extensions.html#EXTEND-EXTENSIONS-SECURITY.

**Comment by cevian** [comment]
Done by https://github.com/timescale/promscale_extension/pull/117
