### ISSUE TITLE
Implement versioned .SO support 

### ISSUE THREAD

**Issue by JamesGuthrie** [timescale/promscale_extension#56]
We would like to version the .so file which we ship with the promscale extension. This allows us to make changes to the extension's C ABI without breaking existing installations.

**Comment by JamesGuthrie** [comment]
We have opened an [issue](https://github.com/zombodb/pgx/issues/343) and corresponding [PR](https://github.com/zombodb/pgx/pull/346) with pgx upstream. They would like have this functionality, but are not sure how yet.

**Comment by cevian** [comment]
@JamesGuthrie can this be closed?

**Comment by JamesGuthrie** [comment]
I guess so. I would still like to have this upstreamed. I guess that we can open a new issue for that.
