### ISSUE TITLE
install promscale_extension in centos 7

### ISSUE THREAD

**Issue by AlyssaBetty** [timescale/promscale_extension#59]
The README.md file show that install promscale_extention with apt-get in ubuntu,does it can not install in centos 7?

**Comment by JamesGuthrie** [comment]
If you would like to install the extension on centos, you will need to build it from source. We don't have any instructions specifically for centos, but it should be analogous to ubuntu.

**Comment by AlyssaBetty** [comment]
Thank you,i understand it.I may later try to install it on centos from source.

**Comment by JamesGuthrie** [comment]
We are currently working on providing packages for a number of distributions, so check back in a few weeks.

**Comment by AlyssaBetty** [comment]
@JamesGuthrie  Thank you very much. I look forward to seeing how to deploy this extension on centos. And it's coming to the production environment.
