### ISSUE TITLE
prom_api.set_metric_retention_period should not create new metrics

### ISSUE THREAD

**Issue by jgpruitt** [timescale/promscale_extension#87]
If you pass a metric name that does not exist to `prom_api.set_metric_retention_period` it creates a new metric. This has caused at least one customer issue when they passed hypertable names instead of metric names to the function.

```
SELECT prom_api.set_metric_retention_period(format('%I.%I',hypertable_schema,hypertable_name), INTERVAL '14 days') 
FROM timescaledb_information.hypertables 
;
```

**Comment by cevian** [comment]
Duplicate of #74?

**Comment by jgpruitt** [comment]
Yes. it is a duplicate
