### ISSUE TITLE
Compilation error on ubuntu 20

### ISSUE THREAD

**Issue by emanzx** [timescale/promscale_extension#9]
root@dnsvumlognode:/datadisk1/promscale_extension# RUST_BACKTRACE=1 make 
Makefile:57: warning: overriding recipe for target 'clean'
/usr/lib/postgresql/12/lib/pgxs/src/makefiles/pgxs.mk:355: warning: ignoring old recipe for target 'clean'
cargo build --release 
   Compiling postgres-headers-rs v0.1.0 (https://github.com/timescale/timescale-extension-utils#09896202)
error: failed to run custom build command for `postgres-headers-rs v0.1.0 (https://github.com/timescale/timescale-extension-utils#09896202)`

Caused by:
  process didn't exit successfully: `/datadisk1/promscale_extension/target/release/build/postgres-headers-rs-37980e0604827e8f/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=wrapper.h

--- stderr
thread 'main' panicked at 'function not loaded: clang_createIndex', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.29.3/src/lib.rs:1659:1
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /usr/src/rustc-1.43.0/vendor/backtrace/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /usr/src/rustc-1.43.0/vendor/backtrace/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: std::panicking::begin_panic
  12: std::thread::local::LocalKey<T>::with
  13: clang_sys::clang_createIndex
  14: bindgen::ir::context::BindgenContext::new
  15: bindgen::Builder::generate
  16: build_script_build::parse_headers::main
  17: std::rt::lang_start::{{closure}}
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  21: std::panicking::try
             at src/libstd/panicking.rs:281
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  24: main
  25: __libc_start_main
  26: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

make: *** [Makefile:54: target/release/libpromscale_rs.a] Error 101

**Comment by JamesGuthrie** [comment]
A lot has changed since this issue was filed. Closing as stale.
