### ISSUE TITLE
Drop Extension is Broken

### ISSUE THREAD

**Issue by jgpruitt** [timescale/promscale_extension#95]
Fix broken TestInstallFlagPromscaleExtension

`DROP EXTENSION promscale;` causes:

```
ERROR:  XX000: cache lookup failed for relation 0
LOCATION:  getRelationIdentity, objectaddress.c:5860
```

**Comment by JamesGuthrie** [comment]
I've opened an issue in the tsdb repo for this: https://github.com/timescale/timescaledb/issues/4140.

It looks like we should be able to work around this issue by manually inserting the correct values into `pg_depend`.

@cevian do you think that we should a) wait for the fix in TSDB, or b) work around the issue with a manual `pg_depend` entry?

I think that option b makes more sense:
1. decouples us from TSDB release process
2. means that we're not dependent on most recent TSDB (only 2.5.2+)

**Comment by cevian** [comment]
@JamesGuthrie option b sounds fine to me

**Comment by JamesGuthrie** [comment]
We've upgraded to timescaledb 2.6.1 and added a test for this, so the extension can now be dropped 🎉
