### ISSUE TITLE
Not able to remove compression on _ps_trace tables

### ISSUE THREAD

**Issue by JamesGuthrie** [timescale/promscale_extension#98]
If a user runs the following command:

`ALTER TABLE _ps_trace.span SET (timescaledb.compress=false);`

Then they will get this error:

```
ERROR:  2BP01: cannot drop table _timescaledb_internal._compressed_hypertable_4 because extension promscale requires it
HINT:  You can drop extension promscale instead.
LOCATION:  findDependentObjects, dependency.c:819
```

On the one hand, we're not certain if this is something which we want users to be able to do. On the other hand it could also _possibly_ be a bug in timescaledb.

**Comment by cevian** [comment]
I think this can be fixed with
```
alter extension promscale drop table x;
alter table x set ...;
alter extension promscale add table x;
```
if the user really wants. I'd vote for closing this as a don't fix for now. @JamesGuthrie thoughts?

**Comment by JamesGuthrie** [comment]
Okay, let's close as won't fix.
